name: Publish Docker images

on:
  push:
    tags:
    - "*"

jobs:
  docker-image-2-0:
    name: v2.0
    if: github.event_name == 'push' && contains(github.ref, 'v2.0.')
    runs-on: ubuntu-18.04
    env:
      IMAGE_NAME: docker.pkg.github.com/${{ github.repository }}/linux:2.0
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    timeout-minutes: 10
